### PR TITLE
Update to Version 6.4.0

### PR DESCRIPTION
**Pull request by rxm7706**
1. There is something different / new about sass, where referential path to the style sheet is not being picked up, perhaps because of where sass is running on conda-forge vs the development process.  Compiling fails saying cannot find '../../../../node_modules/highlight.js/styles/a11y-light'. So  I am still using a modified copy of metadata-code-themes.scss

[/src/components/metadata/styles/](https://github.com/kedro-org/kedro-viz/blob/main/src/components/metadata/styles/metadata-code-themes.scss)

That changes 

```
  @include meta.load-css(
    '../../../../node_modules/highlight.js/styles/a11y-light'
  );
}
```

to 

```
  @include meta.load-css(
    './a11y-light'
  );
}
```

That requires placing a copy of both a11y-light.css and a11y-dark.css in the same folder as metadata-code-themes.scss
[/src/components/metadata/styles/](https://github.com/kedro-org/kedro-viz/blob/main/src/components/metadata/styles/)

2. npm install --save react@17.0.2 react-dom@17.0.2 sass@1.54.4 react-scripts@4.0.3 cypress@12.14.0 is needed for https://github.com/kedro-org/kedro-viz/blob/main/package.json to execute. 

3. NODE_OPTIONS=--openssl-legacy-provider was added as an option before running NPM build @astrojuanlu 

4. HTML and Static files from build need to be copied to /package/kedro_viz/html

5. scikit-learn has dropped max_features="auto"  https://github.com/kedro-org/kedro-viz/blob/main/demo-project/conf/base/parameters/modelling.yml#L24 https://github.com/scikit-learn/scikit-learn/pull/20255 I had to change that to max_features: 'sqrt'

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
@millsks @NeroOkwa

I was able to test kedro-viz==6.4.0 locally - and run the kedro-demo locally ; was able to see preview datasets and experiment tracking.

@astrojuanlu kedro-demo project in kedro-viz seems a bit outdated (packages etc) 
also https://github.com/kedro-org/kedro-viz/blob/main/demo-project/conf/base/parameters/modelling.yml#L24
scikit-learn has dropped max_features="auto"
https://github.com/scikit-learn/scikit-learn/pull/20255
I had to change that to max_features: 'sqrt'

Test Screen Shots Below
image

image

**Review by elanqo — APPROVED** [review]
Looks 👍

**Comment by astrojuanlu** [comment]
> @astrojuanlu kedro-demo project in kedro-viz seems a bit outdated (packages etc)
also https://github.com/kedro-org/kedro-viz/blob/main/demo-project/conf/base/parameters/modelling.yml#L24
scikit-learn has dropped max_features="auto"
https://github.com/scikit-learn/scikit-learn/pull/20255
I had to change that to max_features: 'sqrt'

Could you please open an issue upstream, for visibility? cc @tynandebold 

Also, I tested the previous version and looks good, so I'm confident that this one will work as well ⭐ Thanks folks!

**Pull request merged**
