### PR TITLE
Add httpx to recipe to solver for missing dependency

### PR DESCRIPTION
**Pull request by millsks**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by millsks** [comment]
@conda-forge-admin, please rerender

**Comment by millsks** [comment]
@conda-forge-admin, please restart ci

**Review by zaigner — APPROVED** [review]

**Comment by millsks** [comment]
The checks were failing due to an internal 500 error with a quay service that they use during their docker step.

https://github.com/conda-forge/conda-forge.github.io/issues/2017

**Comment by rxm7706** [comment]
Good this failed - Lets not rush on these - httpx is needed by airflow (flask) and this pin could interfere with Airflow.

**Pull request merged**
